### PR TITLE
Fix couple of bugs from the Haxe port

### PR DESCRIPTION
**Pull request by Tw1ddle**
This fixes a couple of bugs that I noticed carried over from my Haxe port.

### CODE REVIEW

**Comment by alexbirkett** [comment]
Hi, thanks for this! I've merged yonsunCN's changes into master so you are welcome to send pull requests there now.

What does this fix exactly? Can you provide a test case that fails that this then fixes?

**Comment by Tw1ddle** [comment]
Will do. yonsunCN fixed the Row.java bug, so that change may be redundant. I'll open another PR for the other two bugs.

**Comment by alexbirkett** [comment]
I went with your implementation.

**Comment by Tw1ddle** [comment]
:+1:

**Pull request closed without merging**
