### PR TITLE
Remove deep copy method

### PR DESCRIPTION
**Pull request by alexbirkett**
The copy constructor does the same thing

### CODE REVIEW

**Comment by alexbirkett** [comment]
Any comments on this @Tw1ddle and @yongsunCN, am I missing something?

**Comment by Tw1ddle** [comment]
No, I think it should just copy the row. It's there because Haxe doesn't have copy constructors.

**Comment by alexbirkett** [comment]
@yongsunCN added the `deepCopy()` method when he finished the port.

**Comment by yongsunCN** [comment]
I think deepCopy is not necessary, I added it only because i saw haxe code has it (I don't know haxe much)

**Pull request merged**
