### PR TITLE
Add missed dualOptimize calls and mistake in dualOptimize method

### PR DESCRIPTION
**Pull request by Tw1ddle**
These bugs carried over from my Haxe port. The changes should bring this in line with the C++ Kiwi implementation.

### CODE REVIEW

**Comment by alexbirkett** [comment]
Thanks for this. It's somewhat alarming that the tests did not catch these errors. Can you think of a way to write a unit test to catch these errors?

**Comment by alexbirkett** [comment]
Well the suggestValue call has no tests, that would be a start :)

**Comment by Tw1ddle** [comment]
For suggestValue, assert that the infeasibleRows array is empty after suggestValue is called. If it isn't empty then dualOptimize was either not called, else an UnknownEditVariable or InternalSolverError must have been thrown.

**Comment by alexbirkett** [comment]
Thanks

**Pull request merged**
