### PR TITLE
completed all the missing part from c++, fixed bugs, passed real world test

### PR DESCRIPTION
**Pull request by yongsunCN**
Hi Alex, thanks for the great work you have done on this kiwi java project. I picked it up and added all the missing pieces from the original c++ code, fixed one or two bugs that might be introduced during your porting, and it seems passed the real world test. 

I also tested the functionalities of removeConstraint and editVariable, it seems that this code now actually works.

### CODE REVIEW

**Comment by alexbirkett** [comment]
I spent a weekend on this nearly a year ago and never made it work properly. I'll check out your pull request!

**Comment by alexbirkett** [comment]
I get a `diamond operator is not supported in -source 1.6` error when I attempted to import the project into Android Studio (IntelliJ based IDE). Happy to switch to a different Java version so long as the library can be used on Android.

**Comment by alexbirkett** [comment]
Great work making the tests pass! I did this porting without a deep understanding of how the Cassowary algorithm works. I was naively hoping to get some of the performance improvements promised by Kiwi C++: 

"Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x." 

Sadly, at first glance, our implementation does not appear to perform any better than Cassowary. I ran a benchmark that adds constraints to a solver (I sent it to you as a pull request)

**Comment by yongsunCN** [comment]
So sad to hear it, I started looking into this repo for the same reason, however this kiwi code looks much simpler than the original cassowary code, which made it a reasonable alternative. 
I'll take a look at your benchmark, thanks for your response.

**Comment by alexbirkett** [comment]
I've manually merged in most of this pull request

**Pull request closed without merging**
